### ISSUE TITLE
Problem with non-ASCII characters

### ISSUE THREAD

**Issue by source-data** [substance/sourcedata-smartfigure-editor#38] opened 2020-01-15 11:20 UTC
When editing text by inserting a non-ASCII character, eg an emoji or a math symbol, further editing of the text makes this character disappear and shifts the cursor in an unexpected way.

For example, if I insert anywhere in the text "This is the title" the emoji 🇨🇭, subsequently adding a point at the end of the title will make the emoji disappear. Same thing with one of the first non-ASCII character ¡

Start:
![image](https://user-images.githubusercontent.com/23602/72429801-0ca2c180-3791-11ea-855b-c83597ee1504.png)

Adding emoji:
![image](https://user-images.githubusercontent.com/23602/72429835-1fb59180-3791-11ea-9013-27b120d447d4.png)

Adding a dot _at the end_:
![image](https://user-images.githubusercontent.com/23602/72429893-378d1580-3791-11ea-8f2c-f1fab64faceb.png)

**Comment by oliver----** [comment] 2020-02-29 00:30
I have identified a deficiency that is easy to fix.
However, I could not reproduce exactly what you have been observing.
In my case, the app was crashing when trying to delete a unicode character partially.
The swiss flag essentially consists of four characters, actually two so called surrogate pairs.
Deleting a halve of such a pair, left my app crashing. But I couldn't see that 'offset displacement'

I will roll out a fix, but then we need to re-evaluate if you still observe this problem.

**Comment by oliver----** [comment] 2020-03-05 10:33
Closing this as IMO it is fixed now. Re-open if it turns out that this is still a problem with the new version.

**Closed by oliver----** 2020-03-05 10:33 UTC
